### ISSUE TITLE
Need to implement abort method

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-oauth2waad#2]
With the `oaut2waad` plugin loaded, if I raise a 401 on my extension with `p.toolkit.abort(401, 'msg')` I get the following:

```
File '/home/adria/dev/pyenvs/glasgow/src/ckanext-glasgow/ckanext/glasgow/controllers/dataset.py', line 50 in new_resource
  p.toolkit._('Unauthorized to create a resource for this package'))
File '/home/adria/dev/pyenvs/glasgow/src/ckan/ckan/lib/base.py', line 58 in abort
  (status_code, detail, headers, comment) = result
TypeError: 'NoneType' object is not iterable
```

@seanh  I guess you need to either implement the `abort` method or do:

`plugins.implements(plugins.IAuthenticator, inherit=True)`

**Comment by amercader** [comment]
**Update** actually, you are implementing an abort method, you just need to return the expected value:

`return (status_code, detail, headers, comment)`

**Comment by amercader** [comment]
Also, why do we need to delete the session items on an abort? You might not be allowed to do some action but still want to be logged in?

**Comment by seanh** [comment]
I thought abort() was called when CKAN aborts a login mid-way for some reason. It's called whenever someone aborts a request? Why does IAuthenticator have that then? Not sure what it's for
